### ISSUE TITLE
Lighthouse stuck in "Lighthouse is warming up"

### ISSUE THREAD

**Issue by pratikborsadiya** [ChromeDevTools/devtools-frontend#76] opened 2018-05-16 12:29 UTC
Running a Lighthouse report on any website results in the Audit tab being stuck in "Lighthouse is warming up" state. This is reproducible on most Linux Systems and Mac OS as well. It seems to work fine on a windows system though.

Refer #69 For more reports.

A new issue is created because the issue #69 is closed while the issue still persists.

![screencast-from-wednesday-16-may-2018-05_51_26-ist](https://user-images.githubusercontent.com/7806891/40116888-c1f2a7b0-5932-11e8-982f-475c32a9496c.gif)

**Comment by nise** [comment] 2018-05-22 10:48
I have the same problem on Ubuntu 16.04 and Chromium Version 66.0.3359.139.

**Comment by patrickallaert** [comment] 2018-05-25 07:16
I was able to reproduce it on Gentoo Linux with versions 66.0.3359.139 and 66.0.3359.170.
However, using version 67.0.3396.40 seems to fix it!

**Comment by pratikborsadiya** [comment] 2018-06-01 07:56
Chromium version 67 was released today fixing the issue.

**Comment by paulirish** [comment] 2018-06-26 19:27
This only affected non-Chrome builds of Chromium. 
It's been fixed by @patrickhulce  in 69.0.3456.0
https://chromium-review.googlesource.com/c/chromium/src/+/1090110

**Comment by tyler36** [comment] 2018-07-25 02:14
Updated to Chrome Version 68.0.3440.75 (Official Build) (64-bit) this morning.
Started having same issue.

OS: Win10 x64

**Comment by mopig** [comment] 2018-07-25 09:11
> same issue

env: macOS => Version 68.0.3440.75 (Official Build) (64-bit)

**Comment by pratikborsadiya** [comment] 2018-07-25 09:22
I can also confirm this issue on Chrome Version 68.0.3440.75 (Official Build) (64-bit) on Windows 10.

**Comment by patrickhulce** [comment] 2018-07-25 14:43
Can confirm that this is a problem with the DevTools remote modules in Chrome 68. Module code for audits, a11y, device art, etc can't be downloaded at the moment.

It's an infrastructure issue that we're working on to fix.

**Comment by tyler36** [comment] 2018-07-25 23:53
Confirmed working for me now. Thanks.

**Comment by skjnldsv** [comment] 2018-07-27 15:37
Same! Thanks! :tada:

**Comment by JamesCatt** [comment] 2018-07-30 16:04
Confirmed working here as well, thanks!

**Closed** 2018-07-30 18:13 UTC

**Comment by jdwill916** [comment] 2018-08-02 15:59
I continue to have this issue on Chrome 68.0.3440.84.

**Comment by mfkvfn** [comment] 2018-08-28 04:59
able to reproduce it

OS: Win 10 64 bit
Chrome: 68.0.3440.106（64 bit）

**Comment by maus86** [comment] 2018-09-12 09:00
same issue

OS: macOS 10.13.6
Chrome: 69.0.3497.92（64 bit)

**Comment by tomymehdi** [comment] 2018-09-19 12:41
Same issue here:

OS: MacOS 10.13.6
Chrome: 69.0.3497.100 (Official Build) (64-bit)

**Comment by yeatszhang** [comment] 2018-09-29 06:49
Same issue here:

OS: MacOS 10.13.6
Chrome: 69.0.3497.100 (Official Build) (64-bit)

**Comment by rajalshah** [comment] 2018-10-13 02:45
Same issue here:

OS: MacOS 10.13.6
Chrome: 69.0.3497.100 (Official Build) (64-bit)

**Comment by cccaballero** [comment] 2018-10-16 20:58
Same issue here:

OS: Ubuntu 18.04
Chrome: 70.0.3538.67 (Oficial build) (64 bits)

**Comment by mfkvfn** [comment] 2018-10-25 01:37
Same issue here:

OS: Windows 10 64bit
Chrome:70.0.3538.77

**Comment by fattypiggy** [comment] 2018-11-08 06:03
Same issue here
OS: MacOS 10.14.1
Chrome: 70.0.3538.77 64bit

**Comment by iTzMeRafa** [comment] 2018-11-14 19:45
I found a workaround.
Install the lighthouse extension for chrome:
https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk/related

This should work at least

**Comment by deepkolos** [comment] 2018-12-05 02:01
it only works few times at the begining, but not all the time, even reinstall chrome or restart computer

OS: Win 7
Chrome: 70.0.3538.110 64bit

**Comment by mirismaili** [comment] 2019-01-17 09:14
Same issue:
Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
OS: Windows 10 (64bit)

**Comment by micahmills** [comment] 2019-01-29 11:01
Same issue:
Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
OS: MacOS 10.14.2

also on Chrome Canary 
Version 74.0.3687.0 (Official Build) canary (64-bit)

**Comment by yinsang** [comment] 2019-02-19 07:54
**You my need open your VPN.**
I am Chinese.
Because of [Chinese GFW](https://zh.wikipedia.org/zh-hans/%E9%98%B2%E7%81%AB%E9%95%BF%E5%9F%8E), I cannot visit many website like google and facebook.
This time my chrome  audits is blocked in "Lighthouse is warming up".
When I open my [Shadowsocks](https://zh.wikipedia.org/wiki/Shadowsocks), I can visit these website out of the GFW.
This time I can use audits of chrome.
